const generateAlias = (uuid) => {
  const adjectives = [
    "Quantum",
    "Async",
    "Recursive",
    "Atomic",
    "Neural",
    "Parallel",
    "Distributed",
    "Dynamic",
    "Static",
    "Virtual",
    "Encrypted",
    "Bitwise",
    "Modular",
    "Reactive",
    "Concurrent",
    "Deterministic",
    "Probabilistic",
    "Lazy",
    "Eager",
    "Immutable",
    "Mutable",
    "Optimized",
    "Compiled",
    "Interpreted",
    "Secure",
    "Unsafe",
    "Robust",
    "Faulty",
    "Resilient",
    "Scalable",
    "Portable",
    "CrossPlatform",
    "Native",
    "Synthetic",
    "Analog",
    "Digital",
    "Binary",
    "Hexadecimal",
    "Octal",
    "Symbolic",
    "Numeric",
    "Logical",
    "Abstract",
    "Concrete",
    "Functional",
    "Declarative",
    "Imperative",
    "Procedural",
    "ObjectOriented",
    "EventDriven",
    "Streamed",
    "Buffered",
    "Cached",
    "Indexed",
    "Serialized",
    "Deserialized",
    "Compressed",
    "EncryptedFast",
    "Threaded",
    "Parallelized",
    "Vectorized",
    "Matrix",
    "Sparse",
    "Dense",
    "Linear",
    "Nonlinear",
    "Randomized",
    "Seeded",
    "Hashed",
    "Signed",
    "Unsigned",
    "Versioned",
    "Forked",
    "Cloned",
    "Merged",
    "Patched",
    "Refactored",
    "Optimistic",
    "Pessimistic",
    "Greedy",
    "Backtracking",
    "Heuristic",
    "Adaptive",
    "Predictive",
    "Generative",
    "Cognitive",
    "Autonomous",
    "Agentic",
    "DistributedFast",
    "Decentralized",
    "Centralized",
    "Synchronous",
    "Asynchronous",
    "Realtime",
    "Batch",
    "Incremental",
    "LazyLoaded",
    "Precomputed",
    "Cold",
    "Hot",
  ];
  const nouns = [
    "Ninja",
    "Wizard",
    "Hacker",
    "Samurai",
    "Ghost",
    "Bandit",
    "Overlord",
    "Debugger",
    "Compiler",
    "Kernel",
    "Daemon",
    "Architect",
    "Engineer",
    "Coder",
    "Programmer",
    "Builder",
    "Breaker",
    "Fixer",
    "Operator",
    "Maintainer",
    "Tester",
    "Analyst",
    "Designer",
    "Optimizer",
    "Scheduler",
    "Parser",
    "Lexer",
    "Interpreter",
    "Executor",
    "Thread",
    "Process",
    "Pipeline",
    "Stack",
    "Queue",
    "Heap",
    "Buffer",
    "Cache",
    "Index",
    "Table",
    "Graph",
    "Tree",
    "Node",
    "Edge",
    "Vertex",
    "Cluster",
    "Shard",
    "Replica",
    "Container",
    "Instance",
    "Service",
    "Endpoint",
    "Gateway",
    "Router",
    "Proxy",
    "Bridge",
    "Adapter",
    "Controller",
    "Manager",
    "Handler",
    "Listener",
    "Emitter",
    "Subscriber",
    "Publisher",
    "Agent",
    "Bot",
    "Script",
    "Module",
    "Package",
    "Library",
    "Framework",
    "Engine",
    "Runtime",
    "Sandbox",
    "Shell",
    "Terminal",
    "Console",
    "Interface",
    "Protocol",
    "Socket",
    "Channel",
    "Stream",
    "Packet",
    "Cipher",
    "Hash",
    "Token",
    "Key",
    "Signature",
    "Ledger",
    "Block",
    "Chain",
    "Oracle",
    "Miner",
    "Validator",
    "Explorer",
    "Watcher",
    "Sentinel",
    "Guardian",
    "Scout",
    "Hunter",
    "Seeker",
  ];

  const word1 = adjectives[Math.floor(Math.random() * adjectives.length)];
  const word2 = nouns[Math.floor(Math.random() * nouns.length)];
  const hash = String(uuid).slice(5, 8);

  return `${word1}-${word2}_${hash}`;
};
// console.log(generateAlias(crypto.randomUUID()))
const generateAvatar =  (alias) => {
  const avatar = `https://api.dicebear.com/7.x/bottts/svg?seed=${alias}`;
  return avatar;
};
// console.log(generateAvatar(generateAlias(crypto.randomUUID())));
const gennerateUser = () => {
  const existing = localStorage.getItem("user");
  if (existing) {
    return JSON.parse(existing);
  }
  const uuid = crypto.randomUUID();
  const alias = generateAlias(uuid);
  const avatar = generateAvatar(alias);
  const user = {
    user_uuid: uuid,
    user_alias: alias,
    user_avatar: avatar,
  };

  const localStorageInstance = localStorage.setItem("user" , JSON.stringify(user))
  console.log(localStorageInstance)

  return user;
};

console.log(gennerateUser())
export const getIdentity = () => gennerateUser()

